name: chembl-beaker
channels:
- defaults
- rdkit
- bioconda
- chembl
dependencies:
- pillow==6.1.0
- rdkit==2019.09.02
- lxml==4.4.1
- matplotlib==3.1.1
- pycairo==1.18.1
- chembl_structure_pipeline==1.0.0
- pip:
    - bottle==0.12.18
    - netaddr==0.7.19
    - pymongo==3.10
    - WebTest==2.0
    - gunicorn==20.0